### ISSUE TITLE
我的mmoitems无法正确显示某些ia模型的材质

### ISSUE THREAD

**Issue by LaoK1236** [INSide-734/MMOitems-zh_CN#10]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

6.10

### 问题描述

我用mmoitems插件制作自定义盔甲，但是制作的盔甲有些不会显示IA材质，只显示皮革套装
出现错误的盔甲拿在手上现实的贴图是正确的
直接从itemsadder拿出来的盔甲模型穿在身上也显示正确
但是在用mmoitems插件加上属性和物品名字制作出来后，拿在手上贴图正确，穿在身上只显示皮革套装，并不会显示盔甲模型
mmoitems并没有报错提示
并且我将所有可能影响到模型加载的东西都尝试过了，比如卸载了光影，换了两个MC版本：1.20.1，1.20.4
甚至是更换forge和fabric，但是都没有解决这类问题
我也没有在issues和网络中发现类似问题
请问有没有什么方法可以解决
非常着急，下面是将模型连接到mmoitems后不显示模型只显示皮革套的示例
![45eddc0047ca042c71e67ad8021b381a](https://github.com/user-attachments/assets/36752f6a-c11e-4e36-9224-8535c5a4e87f)
![c0dc0c16d5b3deebf2b983ba1749c7ee](https://github.com/user-attachments/assets/eda7e602-3253-47da-ba32-1627ed02ca92)

下面是从ia的GUI中直接拿出来的模型穿在身上的示例图
![ae26bb675dca6c68e6a897b19eb36dc0](https://github.com/user-attachments/assets/8cc4afaf-e55c-4d9b-b366-210b314babf5)

### 复现步骤

无

### 预期行为

无

### 日志信息

并没有错误的日志信息

### 相关配置

仿制狼灵盔:
  base:
    material: LEATHER_HELMET
    custom-model-data: 70025
    unstackable: true
    name: '&f仿·狼灵盔 &e&l| &f类型：麀'
    lore:
    - '&7 ----------[&8&l介绍&7]----------'
    - '       &f崟 &7结合了篝火之力.         '
    - '       &f崟 &7仿制出了这个玩意儿.      '
    - '&7 ----------[&3&l属性&7]----------'
    - '&3 &7■ &f恝&7 护甲值: &f3.0'
    - '&3 &7■ &f韡&7 生命力: &f4.0'
    - '&3 &7■ &f恝&7 物理防御: &f2.5'
    - '&7 ----------[&a&l强化&7]----------'
    - '&f愙&a&l不可强化'
    - '&f覭&a&l不可神谕'
仿制狼灵甲:
  base:
    material: LEATHER_CHESTPLATE
    custom-model-data: 70030
    unstackable: true
    name: '&f仿·狼灵甲 &e&l| &f类型：麀'
    lore:
    - '&7 ----------[&8&l介绍&7]----------'
    - '       &f崟 &7结合了篝火之力.         '
    - '       &f崟 &7仿制出了这个玩意儿.      '
    - '&7 ----------[&3&l属性&7]----------'
    - '&3 &7■ &f恝&7 护甲值: &f5.0'
    - '&3 &7■ &f韡&7 生命力: &f5.0'
    - '&3 &7■ &f恝&7 物理防御: &f3.5'
    - '&7 ----------[&a&l强化&7]----------'
    - '&f愙&a&l不可强化'
    - '&f覭&a&l不可神谕'
仿制狼灵护腿:
  base:
    material: LEATHER_LEGGINGS
    custom-model-data: 70028
    unstackable: true
    name: '&f仿·狼灵护腿 &e&l| &f类型：麀'
    lore:
    - '&7 ----------[&8&l介绍&7]----------'
    - '       &f崟 &7结合了篝火之力.         '
    - '       &f崟 &7仿制出了这个玩意儿.      '
    - '&7 ----------[&3&l属性&7]----------'
    - '&3 &7■ &f恝&7 护甲值: &f2.0'
    - '&3 &7■ &f韡&7 生命力: &f2.5'
    - '&3 &7■ &f恝&7 物理防御: &f1.5'
    - '&7 ----------[&a&l强化&7]----------'
    - '&f愙&a&l不可强化'
    - '&f覭&a&l不可神谕'
仿制狼灵靴:
  base:
    material: LEATHER_BOOTS
    custom-model-data: 70030
    unstackable: true
    name: '&f仿·狼灵靴 &e&l| &f类型：麀'
    lore:
    - '&7 ----------[&8&l介绍&7]----------'
    - '       &f崟 &7结合了篝火之力.         '
    - '       &f崟 &7仿制出了这个玩意儿.      '
    - '&7 ----------[&3&l属性&7]----------'
    - '&3 &7■ &f恝&7 护甲值: &f1.5'
    - '&3 &7■ &f韡&7 生命力: &f2.5'
    - '&3 &7■ &f恝&7 物理防御: &f1.5'
    - '&7 ----------[&a&l强化&7]----------'
    - '&f愙&a&l不可强化'
    - '&f覭&a&l不可神谕'

**Comment by LaoK1236** [comment]
补充一下，武器类的物品显示都是正常的，只有盔甲是这样

**Comment by INSide-734** [comment]
你好，请确认你的 mi 盔甲配置的 [染色颜色](https://mmoitems.magicmc.top/item-creation/item-stats-and-options.html#%E6%9F%93%E8%89%B2%E9%A2%9C%E8%89%B2) 与 ia 中的一致

如下。注意，需要将 ia 配置中的16进制颜色转换为RGB格式

# itemsadder config

``` yaml
armors_rendering:
  uranium:
    color: '#000002'
    layer_1: items/armor/example
    layer_2: items/armor/example_2
    use_color: false
```

# mmoitems config

``` yaml
base:
    dye-color: 0 0 2
```
