### ISSUE TITLE
你好，最新版的汉化，用不了技能

### ISSUE THREAD

**Issue by itwxb** [INSide-734/MMOitems-zh_CN#2]
客户端1.20.4

**Comment by itwxb** [comment]
![Uploading IMG_9985.png…]()

**Comment by INSide-734** [comment]
请提供完整的 _日志 服务端版本 插件版本 依赖版本_

**Comment by INSide-734** [comment]
你使用的是否为 [Action](https://github.com/MagicMC-Dev/MMOItems-Zh/actions/runs/8633517834) 中的构建版本？
如果不是请使用 Action 中构建的插件与最新的依赖尝试

**Comment by itwxb** [comment]
> 请提供完整的 _日志 服务端版本 插件版本 依赖版本_

你好，非常感谢你的回复。

日志：https://pastebin.com/raw/XmJvAnAy

服务端版本：1.20.4

插件版本：MMOltems-6.10-SNAPSHOT-ZH.dev.1.0.3.jar

依赖版本：MythicLib-dist-1.6.2-20240407.0
70102-35.jar

谢谢

**Comment by INSide-734** [comment]
> > 请提供完整的 _日志 服务端版本 插件版本 依赖版本_
> 
> 你好，非常感谢你的回复。
> 
> 日志：https://pastebin.com/raw/XmJvAnAy
> 
> 服务端版本：1.20.4
> 
> 插件版本：MMOltems-6.10-SNAPSHOT-ZH.dev.1.0.3.jar
> 
> 依赖版本：MythicLib-dist-1.6.2-20240407.0
> 70102-35.jar
> 
> 谢谢
> 

是否尝试过使用 https://github.com/MagicMC-Dev/MMOItems-Zh/actions/runs/8633517834 自动构建的版本？

**Comment by INSide-734** [comment]
已修复，请在最新的 action 中下载

**Comment by itwxb** [comment]
> 已修复，请在最新的 action 中下载

感谢作者大大连夜修复！！！

**Comment by itwxb** [comment]
> 已修复，请在最新的 action 中下载

action指路：https://github.com/MagicMC-Dev/MMOItems-Zh/actions/runs/8769688126
